/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';
import {
  Hero,
} from './models/hero';

declare global {

  namespace StencilComponents {
    interface AppDashboard {

    }
  }

  interface HTMLAppDashboardElement extends StencilComponents.AppDashboard, HTMLStencilElement {}

  var HTMLAppDashboardElement: {
    prototype: HTMLAppDashboardElement;
    new (): HTMLAppDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'app-dashboard': HTMLAppDashboardElement;
  }
  interface ElementTagNameMap {
    'app-dashboard': HTMLAppDashboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-dashboard': JSXElements.AppDashboardAttributes;
    }
  }
  namespace JSXElements {
    export interface AppDashboardAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHeroDetails {
      'hero': Hero;
      'match': MatchResults;
    }
  }

  interface HTMLAppHeroDetailsElement extends StencilComponents.AppHeroDetails, HTMLStencilElement {}

  var HTMLAppHeroDetailsElement: {
    prototype: HTMLAppHeroDetailsElement;
    new (): HTMLAppHeroDetailsElement;
  };
  interface HTMLElementTagNameMap {
    'app-hero-details': HTMLAppHeroDetailsElement;
  }
  interface ElementTagNameMap {
    'app-hero-details': HTMLAppHeroDetailsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-hero-details': JSXElements.AppHeroDetailsAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeroDetailsAttributes extends HTMLAttributes {
      'hero'?: Hero;
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHeroSearch {

    }
  }

  interface HTMLAppHeroSearchElement extends StencilComponents.AppHeroSearch, HTMLStencilElement {}

  var HTMLAppHeroSearchElement: {
    prototype: HTMLAppHeroSearchElement;
    new (): HTMLAppHeroSearchElement;
  };
  interface HTMLElementTagNameMap {
    'app-hero-search': HTMLAppHeroSearchElement;
  }
  interface ElementTagNameMap {
    'app-hero-search': HTMLAppHeroSearchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-hero-search': JSXElements.AppHeroSearchAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeroSearchAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHeroes {

    }
  }

  interface HTMLAppHeroesElement extends StencilComponents.AppHeroes, HTMLStencilElement {}

  var HTMLAppHeroesElement: {
    prototype: HTMLAppHeroesElement;
    new (): HTMLAppHeroesElement;
  };
  interface HTMLElementTagNameMap {
    'app-heroes': HTMLAppHeroesElement;
  }
  interface ElementTagNameMap {
    'app-heroes': HTMLAppHeroesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-heroes': JSXElements.AppHeroesAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeroesAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppMessages {

    }
  }

  interface HTMLAppMessagesElement extends StencilComponents.AppMessages, HTMLStencilElement {}

  var HTMLAppMessagesElement: {
    prototype: HTMLAppMessagesElement;
    new (): HTMLAppMessagesElement;
  };
  interface HTMLElementTagNameMap {
    'app-messages': HTMLAppMessagesElement;
  }
  interface ElementTagNameMap {
    'app-messages': HTMLAppMessagesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-messages': JSXElements.AppMessagesAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMessagesAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
